// d LOGIN
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const LOGIN_EXITOSO = "LOGIN_EXITOSO";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const ACTUALZIAR_CUENTA = "ACTUALZIAR_CUENTA";
export const CODIGO_VERFICACION = "CODIGO_VERFICACION";
// d REGISTRO
export const REGISTRO_ERROR = "REGISTRO_ERROR";
export const REGISTRO_EXITOSO = "REGISTRO_EXITOSO";
export const CERRAR_SESION = "CERRAR_SESION";
export const MENSAJE_ALERTA = "MENSAJE_ALERTA"



// d ALERTA
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const MOSTRAR_ALERTA2 = "MOSTRAR_ALERTA2";

export const OCULTAR_ALERTA2 = "OCULTAR_ALERTA2";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
export const ABRIR_CARD = "ABRIR_CARD";

// d PRODUCTOS
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const PRODUCTO_SELECCIONADO = "PRODUCTO_SELECCIONADO";
export const PRODUCTOS_LISTA = "PRODUCTOS_LISTA";
export const OBTENER_PRODUCTOS_CATEGORIAS = "OBTENER_PRODUCTOS_CATEGORIAS";
export const OBTENER_PRODUCTOS_CLIENTE = "OBTENER_PRODUCTOS_CLIENTE";
export const PRODUCTOS_ERROR = "PRODUCTOS_ERROR";

// d LISTAS
export const OBTENER_LISTAS = "OBTENER_LISTAS";
export const CREAR_LISTAS = "CREAR_LISTAS";
export const LISTA_ACTUAL = "LISTA_ACTUAL";
export const ACTUALIZAR_LISTA = "ACTUALIZAR_LISTA";
export const ELIMINAR_LISTA = "ELIMINAR_LISTA";
export const QUITAR_PRODUCTO = "QUITAR_PRODUCTO";
export const LISTA_ERROR = "LISTA_ERROR";
export const ADD_PRODUCTO_LISTA = "ADD_PRODUCTO_LISTA";
export const ATUALIZAR_CANTIDAD_PRODUCTO = "ATUALIZAR_CANTIDAD_PRODUCTO";
export const ACTUALIZAR_LISTAS = "ACTUALIZAR_LISTAS";

// d elementos
export const OPEN_ELEMENT = "OPEN_ELEMENT";
export const CLOSE_ELEMENT = "CLOSE_ELEMENT";
export const CREAR_ELEMENTO = "CREAR_ELEMENTO";
export const ELIMINAR_ELEMENTO = "ELIMINAR_ELEMENTO";
export const EDITAR_ELEMENTO = "EDITAR_ELEMENTO";

// d direcciones
export const OBTENER_DIRECCIONES = "OPTENER_DIRECCIONES";
export const ELIMINAR_DIRECCIONES = "ELIMINAR_DIRECCIONES";
export const ERROR_DIRECCIONES = "ERROR_DIRECCIONES";
export const ACTUALIZAR_DIRECCION = "ACTUALIZAR_DIRECCION";
export const CREAR_DIRECCION = "CREAR_DIRECCION";
export const SELECCIONAR_DIRECCION = "SELECCIONAR_DIRECCION";

// d pedidos
export const CONFIRMACION_PEDIDO = "CONFIRMACION_PEDIDO";
export const GENERAR_PEDIDO = "GENERAR_PEDIDO";
export const OBTENER_PEDIDOS = "OBTENER_PEDIDOS";
export const OBTENER_CODIGO = "OBTENER_CODIGO";
export const BORRAR_ESTADO_PEDIDO = "BORRAR_ESTADO_PEDIDO";
export const SELECCIONAR_PEDIDO = "SELECCIONAR_PEDIDO";
